apiVersion: v1
kind: Service
metadata:
  name: mrdevops
  labels:
    app: mrdevops 
spec:
  selector:
    app: mrdevops
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 80
    nodeport: 31200
